spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

app.jwt.secret=ZyXwVuTsRqPoNmLkJiHgFfDdCcBbAa1234567890!@#$%^&*
# 1 hour in milliseconds
app.jwt.expiration-ms=3600000
# Default 7 days
app.jwt.refresh-expiration-ms=604800000