spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

app.jwt.secret=ZyXwVuTsRqPoNmLkJiHgFfDdCcBbAa1234567890!@#$%^&*
# 1 hour in milliseconds
app.jwt.expiry=3600000